src/pages/HomeParticipant.vue
Fixes a check for DOB for the consent forms. This will always be null for LEVANTE. 
=> fixing dob check

src/helpers/query/utils.js, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue
This fixes a typo which allows survey to be properly marked as complete. There is another issue where the survey data is not being fetched properly which will be addressed in another PR (Reason for keeping the logs). 
=> fixing typo in survey task id

src/components/ParticipantSidebar.vue, src/helpers/query/utils.js, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue
- Saving survey data regardless of if the user responded. Any unanswered questions will be `null`. 
- Fixing survey data fetching. 
- Rewrote survey data fetching function to be more readable.
- Fixing prop type check for `studentInfo`. The consuming component required an object and we were passing in `null`. Now passing in empty object. 
=> saving all responses for survey, fixing survey data fetching

src/components/ConsentPicker.vue, src/helpers/query/utils.js, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue, src/router/index.js
This fixes the issue where children found their surveys marked as complete from previous kids completing it. The state is now cleared on sign out. 
The only change is in `src/router/index.js`. The rest are formatting / linting changes.
=> Fix - Subsequent children seeing survey marked as complete.

src/translations/de/de-componentTranslations.json, src/translations/de/pageTitles.json, src/translations/exports.js, src/translations/i18n.js
Add German translations for Sign in + Child view.
=> Adding German translations for sign in +child view

src/pages/SignIn.vue
=> Hiding admin SSO

package-lock.json, package.json
=> Core tasks beta16

src/components/CreateAdministration.vue, src/components/CreateOrgs.vue, src/components/RoarDataTable.vue, src/components/VariantCard.vue, src/pages/HomeAdministrator.vue, src/pages/SignIn.vue, src/router/index.js, src/router/sidebarActions.js, src/translations/de/de-componentTranslations.json, src/translations/en/en-componentTranslations.json, src/translations/en/us/en-us-componentTranslations.json, src/translations/es/co/es-co-componentTranslations.json, src/translations/es/es-componentTranslations.json
- Adding translations for the now hidden Google SSO
- Adding some spacing to create orgs drop down button
- Removing "register tasks" page from admin view (Only super admins can see/access it)
_- Note: admins were not using this anyways so might as well simplify their dashboard view._
- Removing demo and test checkboxes from create orgs and create administrations
_- Note: This will be made obsolete when production is up and running_ 
=> sign in page translations, removing test and demo checkboxes

src/pages/LEVANTE/UserSurvey.vue
=> linking survey to admnistration

package-lock.json, package.json, src/components/LanguageSelector.vue, src/translations/i18n.js
- Language selection now persists across reloads. This solves the issue where children were getting their language reset after completing a task. 
- Updating firekit
=> Refactor language setter to save selection across reload

src/components/CreateAdministrator.vue, src/pages/HomeSelector.vue, src/pages/LEVANTE/UserSurvey.vue, src/pages/SignIn.vue
- Routing parents and teachers to survey on login
- Removing userData and userClaims calls that are not needed. Improves login time. 
- Fixes for admin view
- Fixes so admins can be registered without any orgs selected
=> Parent teacher survey routing, admin fixes

src/components/LanguageSelector.vue, src/translations/i18n.js
=> Updating remaining isLevante var to import from helper

src/components/CreateOrgs.vue
This re-enables the ability to create all types of orgs. This is a precursor for a future functionality to allow groups to be a sub org of a district.
=> Re-enable all orgs to be created

package-lock.json, package.json, src/components/CreateOrgs.vue
Reverting the creation of these orgs until we can update the firekit method createOrgs. This allows admins to see the administrations they created. 
=> Reverting creation of education orgs until there is fix in firekit.

src/pages/LEVANTE/UserSurvey.vue
Allows survey to be submitted since the admin id was always null, crashing the submission process.
=> temporary fix so surveys can be submitted

src/pages/LEVANTE/UserSurvey.vue
Fixes language switching on the survey. Now appropriately switches to the selected language. 
=> Fixing language switching on survey

src/composables/useSurveyResponses/useSurveyResponses.js, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue
Survey results are now saved to localStorage on every question answer and page change. This allows the survey to be continued if a user want's to come back to it or loses connection. 
=> Adding logic to continue an incomplete survey

src/components/EditVariantDialog.vue, src/components/TaskPicker.vue, src/components/VariantCard.vue, src/main.js, src/pages/HomeParticipant.vue, src/pages/HomeSelector.vue, src/pages/LEVANTE/RegisterUsers.vue
=> Levante assignment condtions

src/router/index.js
=> german roar tasks

src/components/ConsentModal.vue, src/components/ConsentPicker.vue, src/components/CreateAdministration.vue, src/components/LEVANTE/RegisterUsersInfo.vue, src/helpers/query/legal.js, src/pages/HomeParticipant.vue, src/translations/de/de-componentTranslations.json, src/translations/en/en-componentTranslations.json, src/translations/en/us/en-us-componentTranslations.json, src/translations/es/co/es-co-componentTranslations.json, src/translations/es/es-componentTranslations.json
=> Consent forms (Germany) - Part 1

package-lock.json, package.json
=> core tasks v1.0.0-beta.19

src/components/CardAdministration.vue, src/components/RoarDataTable.vue, src/pages/ProgressReport.vue
Enables progress report view for LEVANTE. Hid some things like filtering columns, exporting the table, and switching views to score report since these do not work.
=> Fixing progress report view for LEVANTE

package-lock.json, package.json
=> updating core tasks to beta 20

src/assets/styles/components/tabview-games.scss, src/components/GameTabs.vue, src/constants/bucket.js, src/helpers/query/users.js, src/helpers/survey.js, src/helpers/surveyInitialization.js, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue, src/store/game.js
=> Survey linking + refactor

src/components/GameTabs.vue, src/components/LanguageSelector.vue, src/components/NavBar.vue, src/components/views/Settings.vue, src/helpers/survey.js, src/helpers/surveyInitialization.js, src/pages/AdminProfile.vue, src/pages/HomeParticipant.vue, src/pages/LEVANTE/UserSurvey.vue, src/router/index.js, src/store/game.js, src/store/survey.js, src/translations/de/de-componentTranslations.json, src/translations/en/en-componentTranslations.json, src/translations/en/us/en-us-componentTranslations.json, src/translations/es/es-componentTranslations.json
=> Survey fixes for audio, progress, and translations

package-lock.json, package.json
=> core tasks bump

src/helpers/index.js, src/pages/LEVANTE/LinkUsers.vue
=> internal ids are now always strings

src/components/LEVANTE/LinkUsersInfo.vue, src/pages/LEVANTE/LinkUsers.vue, src/pages/LEVANTE/RegisterUsers.vue
=> fixing linking page component imports

package-lock.json, package.json, src/components/GameTabs.vue, src/pages/HomeParticipant.vue, src/pages/LEVANTE/LinkUsers.vue
=> Survey completion fix

.github/workflows/deploy-to-dev.yml
=> Sentry release disable

.github/workflows/deploy-to-dev.yml
=> enabling sentry GH action

.github/workflows/deploy-to-dev.yml
=> changing version to use ref name and sha

package-lock.json, package.json
=> core tasks 1.0.0.beta-28

package-lock.json, package.json
=> tasks bump beta 29

src/sentry.js, src/translations/i18n.js
…s file
Changing the language variable in `sentry.js` to use the formattedLocale rather than pull from the vue-i18n package in a vanilla JS file. Adding conditional chaining and fallback text.
=> Sentry translation error fix

src/helpers/index.js, src/pages/HomeAdministrator.vue, src/pages/LEVANTE/LinkUsers.vue, src/pages/LEVANTE/RegisterUsers.vue
=> refactoring validation, handling user errors

src/components/GameTabs.vue
=> MEFS completion fix, refactoring task navigation w/ router-link

src/components/CreateAdministrator.vue
=> Fix - Registering Administrators

src/pages/LEVANTE/RegisterUsers.vue
=> Pluralize org names passed to createUsers cloud function

package-lock.json, src/components/RoarDataTable.vue
Add spacing to progress report status fields
It fixes https://www.notion.so/Add-spacing-to-progress-report-status-fields-183244e26d9b80f5b606e9c786cd5fa8I 
=> fix: add space to report field tables

src/components/auth/SignIn.vue
=> Removing unnecessary checks, fixing email sign in

README.md
Update to README to include how to spin up LEVATE dev environment // build
- [ X] Documentation Update
=> Updating Readme with Levante NPM scripts

launch.json
- [x ] New feature (non-breaking change which adds functionality)
=> add chrome debug configuration

package-lock.json, package.json
=> core tasks beta.32

src/pages/HomeParticipant.vue
=> LHT-604: Making the find function call resistant to null values

package-lock.json, package.json
=> core tasks beta.33

package-lock.json, package.json, src/pages/LEVANTE/RegisterUsers.vue
=> fix LHT-650 test bug

package-lock.json, package.json
=> bug fix LHT-654

package-lock.json, package.json, src/components/VariantCard.vue, src/pages/HomeParticipant.vue, src/pages/LEVANTE/RegisterUsers.vue
=> Password-fix

src/pages/LEVANTE/RegisterUsers.vue
Fixing userType parsing, as well as other columns.
=> Fix userType column parsing

.github/PULL_REQUEST_TEMPLATE.md
This PR simplifies the PR template leaving only what's necessary. 
Reply if you think something should stay or be added.
=> Simplifying PR template

src/components/LEVANTE/LinkUsersInfo.vue, src/pages/LEVANTE/LinkUsers.vue
parentId and teacherId are now optional, no longer blocking user linking. Also removing org checks as we weren't using them in the linking flow.
=> Fix: Linking no longer blocked by rows without parent & teacher id

src/pages/HomeParticipant.vue
Small adjustment to the survey data fetching to only fetch data if the relational data exists.
=> Survey relation data fetching adjustment

src/sentry.js, vite.config.js
=> Adding commitSHA as a process variable and passing it to Sentry as a tag

package-lock.json, package.json
=> task bump and audit fixes

src/components/CardAdministration.vue, src/helpers/plotting.js, src/pages/HomeAdministrator.vue
This PR implements Assignments Homepage redesign changes described in the task https://github.com/levante-framework/levante-dashboard/issues/103
=> Feature: assignments homepage redesign

package-lock.json, package.json
=> task bump beta.36

src/components/RoarDataTable.vue, src/helpers/plotting.js, src/helpers/query/utils.js, src/pages/ProgressReport.vue
This PR includes the changes for Notion ticket [LHT-629](https://www.notion.so/6-Progress-Report-Updates-1a8244e26d9b808eaa1bfa3568716797?pvs=4).
Issue #155 
=> Progress report improvements

package-lock.json, package.json
=> task bump beta.38

src/pages/LEVANTE/__tests__/AddUsers.spec.ts
Hopefully, add a vitest for add user
Sonnet & I wrote this partially as a learning experience for me. But it does seem to work, so I'm passing it along in case it is useful.
=> Add AddUser test

.github/CODEOWNERS, .github/CONTRIBUTING.md
Update a couple legacy ROAR boilerplate files.
Just templates for now, as we aren't actually looking for contributors, and don't have any documentation for them.
=> Boilerplate-update

src/App.vue
This PR fixes https://github.com/levante-framework/levante-dashboard/issues/180
=> Update page titles

src/pages/HomeAdministrator.vue, src/router/index.js
https://github.com/levante-framework/levante-dashboard/issues/190
=> fix: naming changes to Assignment

src/components/tasks/TaskLevante.vue, src/components/tasks/TaskPA.vue, src/components/tasks/TaskSRE.vue, src/components/tasks/TaskSWR.vue, src/composables/mutations/useCompleteAssessmentMutation.js, src/composables/queries/useUserRunPageQuery.js, src/constants/mutationKeys.js, src/store/auth.js
I believe some tasks not being marked as completed are due to silent failure in the completion logic. I've turned the completeAssessment function into a tanstack mutation that will also retry 3 times on failure.
Fixes issue #174 
Firekit PR that is in addition to this change:  https://github.com/levante-framework/levante-firekit/pull/3
=> FIX: Unreliable completions

src/pages/Debug.vue, src/router/index.ts, src/types/package-json.d.ts
This adds a `/debug` page that lists a bunch of properties about the device/ user/ browser/ performance. This should help us with diagnosing a lot of the issues that we see on the field.
- [ x] New feature (non-breaking change which adds functionality)
=> Adding a debug page that lists a bunch of diagnostic info

.eslintrc.json, cypress.config.cjs, package-lock.json, package.json, src/components/OrgPicker.vue, src/composables/queries/useDistrictSchoolsQuery.js, src/composables/queries/useOrgsTableQuery.js, src/helpers/query/orgs.js, src/pages/HomeSelector.vue, src/pages/audience/CreateAudience.vue, src/pages/audience/ListAudiences.vue, src/plugins.ts, vite.config.js, vitest.setup.js
Issue #209
Issue #196 
Org link changes:
- using adminOrgs since this is the full list of orgs
- changing tab name to sites
Other:
- Removing location input and gmaps package
=> org link changes, removing location input and package

src/pages/Debug.vue
This includes the following enhacements:
1. Adds user Info correctly
2. Adds a commit hash along with version numbers
- [x ] New feature (non-breaking change which adds functionality)
=> Adding some more functionality to the Debug.Vue file

index.html
The meta tag should make the app non zoomable on the mobile browsers. This should prevent any unnecessary UI bugs on the core task side of things during administration.
- [x ] New feature (non-breaking change which adds functionality)
=> feat(226): Making the app non zoomable on mobile browsers

src/components/TaskPicker.vue, src/components/VariantCard.vue
https://github.com/levante-framework/levante-dashboard/issues/230
[ ] ~"Selected audience" has Audience lowercase, which is inconsistent with "Select Audience”~ Already done with name change to Group PR
[X] Hearts & Flowers should be under Executive Function 
[X] Pattern Matching should be under Reasoning 
[ ] ~"Selected tasks" → uppercase tasks~ Already done 
[X] Assigned to "students" → uppercase “students”
=> Create Assignments Page - Naming Fixes

src/components/OrgPicker.vue, src/helpers/index.ts, src/pages/groups/CreateGroup.vue, src/pages/users/AddUsers.vue
Issue #248 
Includes changes from #247 
=> Fix groups naming 1

src/pages/groups/CreateGroup.vue, src/pages/users/AddUsers.vue
- Naming fixes for Groups page
- Fixed adding users with a cohort Group type
=> Groups page and Add users fixes

package-lock.json, package.json
- Moves createAdministration logic to Cloud functions
- Renames createAdministration to upsertAdministration
=> firekit 9.12.13

src/components/userInfo/AddUsersInfo.vue, src/components/userInfo/EditUsersInfo.vue
- Fixing the image for edit users example
- Image size styling
=> FIX: Edit users image

src/pages/users/AddUsers.vue
=> FIX: Add users

src/components/EditOrgsForm.vue, src/components/NavBar.vue, src/components/RoarDataTable.vue, src/components/UserActions.vue, src/pages/groups/ListGroups.vue
=> Fixing name in table, other minor changes

src/assets/styles/root/main.scss, src/pages/users/AddUsers.vue
Fix for https://github.com/levante-framework/levante-dashboard/issues/187
=> Fix: Add users Groups Parsing error feedback

src/components/UserActions.vue
=> doc link fix

src/pages/HomeAdministrator.vue
It fixes [#201](https://github.com/levante-framework/levante-dashboard/issues/201)
=> Fix: home admin empty state

src/components/GroupPicker.vue, src/pages/CreateAdministrator.vue, src/pages/CreateAssignment.vue, src/pages/groups/CreateGroup.vue
=> Group Picker naming

src/pages/groups/CreateGroup.vue
=> Cohorts must belong to a site

.eslintrc.json, src/components/EditVariantDialog.vue, src/components/TaskPicker.vue, src/components/VariantCard.vue
- Adding changes to make the age condition work. 
- Removing old unused code
Note: I modified the assignedTo field to only show the condition for the userType. It's cleaner for now. Later we'll do a UI rework to find a better way to list all of the conditions. 
issue #291 
=> Task age condition

src/helpers/survey.ts, src/helpers/surveyInitialization.ts
- Updating the survey response structure to store response times for each response. 
Issue #254 
=> Response times for survey responses

src/components/NavBar.vue, src/components/UserActions.vue
- Changing the navbar order. 
- Fixing deprecated component. 
Issue #294 
=> Navbar Order Change

src/components/EditOrgsForm.vue, src/helpers/query/orgs.js, src/pages/groups/CreateGroup.vue, src/pages/groups/ListGroups.vue, src/pages/users/AddUsers.vue
=> Removing abbreviation field

package-lock.json, package.json, src/components/NavBar.vue, src/logger.ts, src/pages/Debug.vue, src/plugins/posthog.ts, src/router/index.ts, src/router/navbarActions.ts, src/sentry.ts, src/setup.ts, src/store/auth.js, src/vue.d.ts
This PR adds Posthog integration. The idea would be to introduce a logger:
1. Event will fire a posthog event for logging event
2. Error event will a Sentry error
Those should only work for production app. For Staging and local it should log to console.
- [x ] New feature (non-breaking change which adds functionality)
=> Adding Posthog

src/assets/styles/root/variables.scss, src/components/CardAdministration.vue, src/components/RoarDataTable.vue, src/components/userInfo/AddUsersInfo.vue, src/pages/groups/ListGroups.vue, src/plugins.ts
https://github.com/levante-framework/levante-dashboard/issues/300
Color discussion in slack: https://stanford-levante.slack.com/archives/C05UY4Y2Q15/p1747068801877609
- Update primary color
- Updated "hover" / secondary color to be the darker version of that color
- Updated normal text that was either in primary color or had primary color as background to be bold weight
Some screenshots:
=> Update theme to reflect Levante Colors

src/translations/de/de-componentTranslations.json
Update "preparing your game" text as suggested by Mike's contact in Germany
Issue #175
=> update "preparing" text

src/components/EditVariantDialog.vue, src/components/TaskPicker.vue, src/pages/CreateAssignment.vue
=> Participant task names for conditions modal.

src/pages/groups/ListGroups.vue
https://github.com/levante-framework/levante-dashboard/issues/292
Was seeing cohort tab error because using an empty string in routeParams errors out. 
There are some minor UI optimizations that could be made (like showing loading state when moving between tabs) and ocassionally styling within the header looks a little werid. But these both seem like backlog items.
=> Fix cohort tab on List Group Page

.eslintrc.json, src/components/GameTabs.vue, src/constants/bucket.ts, src/helpers/survey.ts, src/pages/HomeParticipant.vue, src/pages/UserSurvey.vue, tsconfig.json
Fixes:
- Audio for the child survey. 
- Game tabs button and title. Correctly marking the survey as complete. 
- Marking the survey as complete if you don't have the specific parts as a caregiver or teacher (no children or classes linked). 
- Only querying survey data if the assignment has the survey. 
- Survey now properly gets initiated if switching to an assignment with the survey. 
Includes #241 
=> Miscellaneous survey fixes

src/components/RoarDataTable.vue, src/pages/groups/ListGroups.vue, src/pages/users/ListUsers.vue
=> Removing stuff not used / not enabled

src/components/tasks/TaskLevante.vue, src/router/navbarActions.ts
=> fix(): Fix tasks not starting

src/components/CardAdministration.vue, src/components/ConsentPicker.vue, src/components/EditUsersForm.vue, src/components/EditVariantDialog.vue, src/components/GameTabs.vue, src/components/GroupPicker.vue, src/components/NavBar.vue, src/components/TaskPicker.vue, src/components/VariantCard.vue
Convert next 10 components to ts
=> Ts-component-second10

src/components/CardAdministration.vue, src/components/UserActions.vue
It fixes https://github.com/levante-framework/levante-dashboard/issues/318 and https://github.com/levante-framework/levante-dashboard/issues/367
=> Fix: Settings layout shift

src/components/auth/SignIn.vue
=> Firekit migration - removing unused auth stuff

src/pages/tests/CreateGroup.test.js
I added unit tests to the Group Creation page.
Unit tests
=> Test #266 Added unit tests for Group Creation page

src/assets/styles/root/base.scss, src/assets/styles/root/container.scss, src/assets/styles/root/main.scss, src/components/CardAdministration.vue, src/components/NavBar.vue, src/components/RoarDataTable.vue, src/components/UserActions.vue, src/components/userInfo/AddUsersInfo.vue, src/components/userInfo/LinkUsersInfo.vue, src/pages/HomeAdministrator.vue, src/pages/ProgressReport.vue
This PR refers to task https://github.com/levante-framework/levante-dashboard/issues/350
https://github.com/user-attachments/assets/0ac18dae-2a09-4562-9d7b-f9d1efc0e938
Top Header: Adjusted proportions, spacing, and menu layout.
Assignments Homepage: Updated content and proportions for Assignment Details; repositioned settings.
Assignment Details: Adjusted proportions.
Add and Link Users: Fixed image sizing to ensure readability. The columns example section now allows horizontal scroll only.
Groups Page: UI improvements addressing two small UI bugs. It should now display as originally intended (no ghost column), as shown in the screenshots attached to the task.
=> Feature: Enhancements for smaller screens

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md
=> issue templates

src/components/tests/NavBar.test.js
I added unit tests to the navbar component for the 3 types of users I found: superAdmin, admin and none of them.
=> Test #268 Added unit tests to the navbar component

src/components/RoarDataTable.vue, src/pages/groups/ListGroups.vue
– Fixed a blank column that appeared on screen resize
– Now showing “--” for UID on admins when missing
=> Fix: Admin rows data

src/components/modals/AddGroupModal.vue, src/components/tests/AddGroupModal.test.js, src/composables/queries/useOrgNameExistsQuery.ts
The ticket is about site names, but the query we have was ready for the other types of groups, so I created a composable to query for every org name/type to avoid duplicates.
**Adding Site**
https://github.com/user-attachments/assets/98d5edec-7c2d-4ed3-8116-ae916d49034c
**Adding School**
https://github.com/user-attachments/assets/95988792-e20a-4531-bb34-6893d31dbdd7
**Adding Class**
https://github.com/user-attachments/assets/495cb8d2-f4e5-4bfe-b36c-34df65232302
**Adding Cohort**
https://github.com/user-attachments/assets/3cfc7aed-7383-48e4-9dfc-e3d9d77f27f8
=> Task #401 Make org names unique

src/components/modals/AddGroupModal.vue, src/composables/mutations/useUpsertOrgMutation.ts, src/composables/queries/useOrgNameExistsQuery.ts, src/helpers/index.ts, src/helpers/query/orgs.js
I added a new function to normalize group names to lowercase so we can search them case-insensitively.
**Adding new group with normalized name**
https://github.com/user-attachments/assets/777145e2-4f50-4e26-bde7-ff63cbd43d33
**Trying to create a group with the same name**
https://github.com/user-attachments/assets/a4bf5664-05ce-48b0-819e-cd9eebbcf2ad
=> Task #412 Normalize group names when creating groups

src/composables/queries/useDistrictsQuery.ts, src/logger.ts, src/pages/HomeParticipant.vue
- [ x] New feature (non-breaking change which adds functionality)
=> feat(): Adding site name to posthog events whenever available

src/components/CardAdministration.vue, src/helpers/query/administrations.js, src/pages/HomeAdministrator.vue, src/pages/ProgressReport.vue
I updated the administration query to include the assignment creator's data.
I also made a few styling updates.
**Assignment card**
**Progress Report page**
=> Task #403 Show who created an assignment

src/pages/users/AddUsers.vue
Updating the org check in add users to use the normalized name. 
=> Fix org name for add users

src/helpers/query/utils.js, src/pages/HomeAdministrator.vue, src/pages/tests/HomeAdministrator.test.js
I created a new utility called `orderByNameASC` to sort assignments by their `name` prop.
=> Bug #461 Fix default orderBy for assignments

src/components/CardAdministration.vue
The edit button was pushing the user to the wrong route name. I changed from `EditAdministration` to `EditAssignment`.
=> Bug #433 Edit assignment broken

package-lock.json, package.json
The only thing this does is add, createAt and updateAt fields for tasks, variants, guests, and trial documents. 
=> firekit bump v9.3.2

package-lock.json, package.json, src/helpers/query/utils.js
=> changing emulator project

src/pages/ProgressReport.vue
Since we already have the username col, I just removed the UID col. Unfortunately, I couldn't display the whole progress report page correctly, so there is no screenshot.
=> Task #456 Replace UID with username on progress report page

package-lock.json, package.json, src/assets/styles/components/navbar.scss, src/components/NavBar.vue, src/pages/HomeParticipant.vue
I removed the dropdown and added both start and end dates for all assignments.
Note: I also made a few layout changes, mostly on the navbar.
**BEFORE**
**AFTER**
=> Feat #515 Participant page redesign - remove dropdown

src/components/SideBar.vue, src/components/assignments/UpcomingAssignments.vue, src/components/tests/SideBar.test.js, src/components/tests/UpcomingAssignments.test.js, src/pages/HomeParticipant.vue
I created a new component to display the upcoming assignments. I also made a few changes to improve code readability.
https://github.com/user-attachments/assets/ba8ff582-00b9-4f3f-acbd-83983d962013
=> Feat #517 Participant page redesign - Upcoming Assignments

src/composables/queries/useOrgsTableQuery.ts, src/helpers/query/orgs.js, src/pages/groups/ListGroups.vue
It was not visible when created by an admin only. For super admins, it was working. I fixed it.
https://github.com/user-attachments/assets/b3134264-9f91-46b2-87b6-302fa552c6a1
Notion ticket link: https://www.notion.so/26a244e26d9b80f4844cee15976c5066?v=26a244e26d9b80d0b00a000c5ac5f2a8&p=26a244e26d9b806589a1c47a6f3f8387&pm=s
=> Bug #556 New site not visible until refresh

src/composables/mutations/useUpsertOrgMutation.ts
https://github.com/levante-framework/levante-dashboard/issues/578
=> fix: fix class query

src/App.vue, src/assets/styles/components/navbar.scss, src/components/SideBar.vue, src/components/tests/SideBar.test.js, src/pages/HomeParticipant.vue, src/pages/SignIn.vue, src/store/assignments.js
The last thing:
https://github.com/user-attachments/assets/af40eba6-c53d-4501-b50f-43f499621de6
=> Bug #555 Participants page redesign minor issues from QA [PART 2]

package-lock.json, package.json, src/components/GameTabs.vue
=> Fixing ROAR task routing, adding back firekit

package-lock.json, package.json, src/components/GameTabs.vue, src/components/GroupPicker.vue
=> Temporarily disable dropdowns in group picker

src/App.vue
=> removing session timeout

src/components/TaskPicker.vue, src/pages/CreateAssignment.vue
I refactored the onChange function of the search field. I took the opportunity to make a few small changes to the code to improve readability.
=> Bug #619 Inconsistent task picker search
